# Generated by Django 5.0.6 on 2024-07-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_savat_name_savat_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savat',
            name='cost',
        ),
    ]
